name: "Update translations"

on:
  push:
    branches:
      - main
    paths:
      - 'i18n/*'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  translations:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        persist-credentials: false
    - uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Translate1
      run: |
        cd parsers
        python regions_UN_lang.py
    - name: Translate2
      run: |
        cd parsers
        python subregions_UN_lang.py
    - name: Translate3
      run: |
        cd parsers
        python regions_The_World_Bank_lang.py
    - name: Translate4
      run: |
        cd parsers
        python regions_The_World_Factbook_lang.py
    - name: Translate5
      run: |
        cd parsers
        python OBJECTIVE_LISTS_lang.py
    - name: Translate6
      run: |
        cd parsers
        python OBJECTIVE_LISTS_2_lang.py
    - name: Translate7
      run: |
        cd parsers
        python OBJECTIVE_LISTS_3_lang.py
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: Updated translations
